### ISSUE TITLE
consider working with JMESPath

### ISSUE THREAD

**Issue by georgettica** [zakjan/objectpath#11]
JMESPath - https://jmespath.org/ is used in some places and is partially solving the issue this repo is intending to solve

not to say this tool isn't awesome, but it's worth knowing how you distinguish from it

**Comment by zakjan** [comment]
Wow, this looks like exactly what I needed. I'll explore it, and potentially I could deprecate my repo. Thanks!

**Comment by zakjan** [comment]
From the first look, it seems the only difference that my library supports basic datetime functions (timestamp <-> ISO conversion). Do you know if JMESPath allows injecting custom functions?

**Comment by georgettica** [comment]
Not sure, but I would guess no

**Comment by georgettica** [comment]
I'm surprised to find this
https://github.com/burtcorp/jmespath-java#adding-custom-functions
So at least some of the implementations have it

**Comment by zakjan** [comment]
Interesting, it seems it's not in the original spec. Might be worth suggesting it there.
