### ISSUE TITLE
join not working for array of numbers

### ISSUE THREAD

**Issue by rpalacio86** [zakjan/objectpath#2]
Hello, thank you for your work. I'm currently testing the library in js. If I have this data
`const sampleData = {
    items: [{id: 1}, {id: 2}]
}`
the path `$.items.map(id)` returns `[1, 2]` 
but the path `join($.items.map(id), ';')` returns `null`.
However if the data is 
`const sampleData = {
    items: [{id: '1'}, {id: '2'}] // Id's now are string
}`
the path `join($.items.map(id), ';')` returns `'1;2'`

Is there any way to achieve the join function to work for array of numbers like javascript does?

**Comment by zakjan** [comment]
Hi, thanks for noticing. It's because `join` function currently expects only strings as inputs. I'll add a conversion function.

**Comment by zakjan** [comment]
Hi @rpalacio86, I've just released 1.0.1 with toString and toNumber functions. Your case is supported by path `join(items.map(toString(id)), ';')`

**Comment by zakjan** [comment]
I'm thinking about a major refactoring of the syntax, to be more jq-like. So this case would be something like `items | map(toString(id)) | join(';')`. What do you think?

**Comment by rpalacio86** [comment]
Thank you very mucho Jan! Looks good. I think that the pipes syntax would be more intuitive than the current one.
